# SPDX-License-Identifier: GPL-2.0
dtb-y += dtbo/exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A30_OPEN) := \
	dtbo/exynos7904-a30_chn_open_00.dtbo \
	dtbo/exynos7904-a30_chn_open_01.dtbo \
	dtbo/exynos7904-a30_cis_open_00.dtbo \
	dtbo/exynos7904-a30_cis_open_01.dtbo \
	dtbo/exynos7904-a30_cis_open_02.dtbo \
	dtbo/exynos7904-a30_swa_open_00.dtbo \
	dtbo/exynos7904-a30_swa_open_01.dtbo \
	dtbo/exynos7904-a30_swa_open_02.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
