# SPDX-License-Identifier: GPL-2.0
dtb-y += dtbo/exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A10_OPEN) := \
	dtbo/exynos7884B-a10_eur_open_00.dtbo \
	dtbo/exynos7884B-a10_eur_open_01.dtbo \
	dtbo/exynos7884B-a10_kor_open_00.dtbo \
	dtbo/exynos7884B-a10_kor_open_03.dtbo \
	dtbo/exynos7884B-a10_kor_open_05.dtbo \
	dtbo/exynos7884B-a10_sea_open_00.dtbo \
	dtbo/exynos7884B-a10_swa_open_00.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A20_GLOBAL) := \
	dtbo/exynos7884B-a20_cis_ser_00.dtbo \
	dtbo/exynos7884B-a20_cis_ser_01.dtbo \
	dtbo/exynos7884B-a20_cis_ser_03.dtbo \
	dtbo/exynos7884B-a20_aus_xsa_00.dtbo \
	dtbo/exynos7884B-a20_aus_xsa_01.dtbo \
	dtbo/exynos7884B-a20_aus_xsa_03.dtbo \
	dtbo/exynos7884B-a20_sea_xtc_00.dtbo \
	dtbo/exynos7884B-a20_sea_xtc_01.dtbo \
	dtbo/exynos7884B-a20_sea_xtc_03.dtbo \
	dtbo/exynos7884B-a20_swa_open_00.dtbo \
	dtbo/exynos7884B-a20_swa_open_01.dtbo \
	dtbo/exynos7884B-a20_swa_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A20e_OPEN) := \
	dtbo/exynos7884B-a20e_eur_open_00.dtbo \
	dtbo/exynos7884B-a20e_eur_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A30_OPEN) := \
	dtbo/exynos7904-a30_chn_open_00.dtbo \
	dtbo/exynos7904-a30_chn_open_01.dtbo \
	dtbo/exynos7904-a30_cis_open_00.dtbo \
	dtbo/exynos7904-a30_cis_open_01.dtbo \
	dtbo/exynos7904-a30_cis_open_02.dtbo \
	dtbo/exynos7904-a30_swa_open_00.dtbo \
	dtbo/exynos7904-a30_swa_open_01.dtbo \
	dtbo/exynos7904-a30_swa_open_02.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A30s_OPEN) := \
	dtbo/exynos7904-a30s_eur_open_00.dtbo \
	dtbo/exynos7904-a30s_eur_open_01.dtbo \
	dtbo/exynos7904-a30s_eur_open_02.dtbo \
	dtbo/exynos7904-a30s_eur_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A40_OPEN) := \
	dtbo/exynos7904-a40_eur_open_00.dtbo \
	dtbo/exynos7904-a40_eur_open_01.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
